import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import NavBarContainer from "@/components/navbar/NavBarContainer";
import { ToastContainer } from 'react-toastify';
import { CartProvider } from "@/context/CartContext";

const ubuntu = Ubuntu({
  weight: ["400", "500", "700"], // Changed "600" to "700"
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AsteroiDMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body className="" suppressHydrationWarning={true}>
        <main className="w-full">
          {/* <NavBar /> */}
          <CartProvider>
            <NavBarContainer />
            <ToastContainer />
            {children}
            <Footer />
          </CartProvider>
        </main>
      </body>
    </html>
  );
}
